[package]
name = "iot-monitoring-backend"
version = "0.1.0"
edition = "2021"

[dependencies]

# API
axum = { version = "0.8", features = ["ws"] }

tokio = { version = "1", features = ["full"] }

tower-http = { version = "0.6", features = ["cors", "trace", "request-id"] }

serde = { version = "1", features = ["derive"] }

serde_json = "1"
sha2 = "0.10"

# Base de données
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
    "chrono",
    "migrate"
] }

# JWT
jsonwebtoken = "9"

# Password
argon2 = "0.5"

# UUID
uuid = { version = "1", features = ["v4","serde"] }

# Date
chrono = { version = "0.4", features = ["serde"] }

# Variables d'environnement
dotenvy = "0.15"

# MQTT
rumqttc = "0.24"

# Validation
validator = { version = "0.20", features = ["derive"] }

# Logs
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
